import * as React from "react";
import Image from "next/image";
import Link from "next/link";

import { cn } from "@/lib/utils";

/**
 * The TESLA Electronics brand mark and lockup.
 *
 * Both render the supplied logo artwork from `public/brand/`, generated by
 * `scripts/generate-icons.mjs` from `tesla-electronics-logo.png`. Re-run that
 * script after replacing the source and every derivative — favicon, PWA icons,
 * link-preview card — updates with it.
 *
 * ---------------------------------------------------------------------------
 * Two variants, because the artwork is light-on-dark
 * ---------------------------------------------------------------------------
 * The logo is chrome on black. Cut out with alpha taken from luminance it
 * composites perfectly over any dark surface — and vanishes on the product's
 * ivory one, where mid-grey chrome becomes near-transparent white. So:
 *
 *   · `plate` — the cutout on a dark rounded badge. Safe anywhere, and the
 *     default. This is what appears in headers, navigation and on white cards.
 *   · `bare`  — the cutout alone. Dark surfaces only: the wallet's charcoal
 *     panel, the auth brand panel, anything using `tone="inverse"`.
 *
 * Note on trademark: this artwork reproduces Tesla, Inc.'s "T" device and TESLA
 * wordmark. It is used here at the product owner's direction. This file makes no
 * claim that the mark is original to this platform — see
 * `siteConfig.affiliationDisclaimer` for the platform's stated relationship.
 */

const MARK_PLATE = "/brand/logo-mark-plate.png";
const MARK_BARE = "/brand/logo-mark.png";
const LOCKUP = "/brand/logo-lockup.png";

export type LogoVariant = "plate" | "bare";

type LogoMarkProps = Omit<React.ComponentProps<"span">, "children"> & {
  variant?: LogoVariant;
  /** Loads eagerly. Set on the shell header so the mark never pops in. */
  priority?: boolean;
};

/**
 * The mark on its own — ring and monogram, no type.
 *
 * Sized entirely by `className` (`size-8`, `size-full`, …). The image fills the
 * span, so the caller controls dimensions exactly as it did when this was an
 * inline SVG.
 */
export function LogoMark({
  className,
  variant = "plate",
  priority = false,
  ...props
}: LogoMarkProps) {
  return (
    <span
      className={cn(
        "relative block size-8 shrink-0 overflow-hidden",
        variant === "plate" && "rounded-[23%]",
        className
      )}
      {...props}
    >
      <Image
        src={variant === "plate" ? MARK_PLATE : MARK_BARE}
        alt=""
        aria-hidden="true"
        fill
        sizes="64px"
        priority={priority}
        className="object-contain"
      />
    </span>
  );
}

const lockupSizes = {
  xs: { width: 128, height: 96 },
  sm: { width: 168, height: 126 },
  md: { width: 224, height: 168 },
  lg: { width: 320, height: 240 },
} as const;

/**
 * The full artwork — mark, TESLA wordmark and the ELECTRONICS line.
 *
 * For dark surfaces with room to breathe. Below roughly 160px wide the
 * ELECTRONICS line stops being legible, which is why the header uses `Logo`
 * (mark plus live type) rather than this.
 */
export function LogoLockup({
  className,
  size = "md",
  priority = false,
}: {
  className?: string;
  size?: keyof typeof lockupSizes;
  priority?: boolean;
}) {
  const { width, height } = lockupSizes[size];

  return (
    <Image
      src={LOCKUP}
      alt="TESLA Electronics"
      width={width}
      height={height}
      priority={priority}
      sizes={`${width * 2}px`}
      className={cn("h-auto w-full object-contain", className)}
    />
  );
}

type LogoProps = {
  className?: string;
  /** Hides the wordmark, leaving the mark alone (compact headers, avatars). */
  markOnly?: boolean;
  size?: "xs" | "sm" | "md" | "lg";
  /** Renders as a plain element instead of a link. */
  asLink?: boolean;
  /** Where the lockup links to. Defaults to the marketing home page. */
  href?: string;
  /**
   * Forces a mark variant. Normally left alone: `tone` already implies it, since
   * `inverse` means the surface is dark.
   */
  variant?: LogoVariant;
  /** Inverts the wordmark for use on the charcoal panel. */
  tone?: "default" | "inverse";
  priority?: boolean;
};

const wordmarkSizes = {
  xs: { text: "text-[0.8rem]", mark: "size-6", gap: "gap-2" },
  sm: { text: "text-[0.95rem]", mark: "size-7", gap: "gap-2.5" },
  md: { text: "text-[1.05rem]", mark: "size-8", gap: "gap-2.5" },
  lg: { text: "text-xl", mark: "size-10", gap: "gap-3" },
} as const;

/**
 * The horizontal lockup: mark plus live type.
 *
 * The wordmark stays real text rather than part of the image. At header sizes the
 * artwork's own type would be 12px tall and its ELECTRONICS line under 3px —
 * illegible, and unreadable to a screen reader too. `LogoLockup` is there for the
 * places with room for the full artwork.
 */
export function Logo({
  className,
  markOnly = false,
  size = "md",
  asLink = true,
  href = "/",
  variant,
  tone = "default",
  priority = false,
}: LogoProps) {
  const sizes = wordmarkSizes[size];
  const inverse = tone === "inverse";
  // A dark badge on an already-dark panel reads as a hole. Bare is correct there.
  const markVariant: LogoVariant = variant ?? (inverse ? "bare" : "plate");

  const content = (
    <span
      className={cn(
        "inline-flex items-center transition-opacity",
        sizes.gap,
        inverse ? "text-surface-inverse-foreground" : "text-foreground",
        asLink && "hover:opacity-80",
        className
      )}
    >
      <LogoMark
        variant={markVariant}
        priority={priority}
        className={sizes.mark}
      />
      {!markOnly && (
        <span className="flex items-baseline gap-[0.32em] leading-none whitespace-nowrap">
          <span
            className={cn("font-semibold tracking-[0.15em] uppercase", sizes.text)}
          >
            Tesla
          </span>
          <span
            className={cn(
              "font-light tracking-[0.02em]",
              inverse
                ? "text-surface-inverse-foreground/65"
                : "text-muted-foreground",
              sizes.text
            )}
          >
            Electronics
          </span>
        </span>
      )}
    </span>
  );

  if (!asLink) return content;

  return (
    <Link
      href={href}
      aria-label="TESLA Electronics — home"
      className="rounded-md focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-brand"
    >
      {content}
    </Link>
  );
}
